import { Link } from "react-router-dom";

export default function PrivacyPage() {
  return (
    <div className="legal-page">
      <div className="legal-content">
        <h1 className="legal-title">Privacy Policy</h1>
        <p className="legal-updated">Last updated: March 26, 2026</p>

        <section className="legal-section">
          <h2>1. Introduction</h2>
          <p>
            ViolaWake ("we", "us", "our") operates the ViolaWake Console web
            application and the ViolaWake SDK. This Privacy Policy explains how
            we collect, use, disclose, and safeguard your information when you
            use our services. By accessing or using ViolaWake, you agree to the
            terms of this Privacy Policy.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Information We Collect</h2>

          <h3>2.1 Account Information</h3>
          <p>
            When you register for a ViolaWake Console account, we collect your
            email address, display name, and a hashed version of your password.
            We never store passwords in plaintext.
          </p>

          <h3>2.2 Voice Recordings</h3>
          <p>
            When you use the Console to train a custom wake word model, you
            record audio samples through your browser. These recordings are
            uploaded to our servers solely for the purpose of training your wake
            word model. Recordings are stored temporarily during the training
            process and are automatically deleted within 30 days of model
            completion. You may also delete recordings manually at any time
            through the Console dashboard.
          </p>

          <h3>2.3 Trained Models</h3>
          <p>
            Wake word models (.onnx files) generated by our training pipeline
            are stored in your account until you delete them or close your
            account. Models are associated with your account and are not shared
            with other users.
          </p>

          <h3>2.4 Usage Data</h3>
          <p>
            We collect anonymized usage data including pages visited, training
            jobs initiated, and feature usage patterns. This data helps us
            improve the service and is not linked to your voice recordings.
          </p>

          <h3>2.5 Payment Information</h3>
          <p>
            Payment processing is handled entirely by Stripe, Inc. We do not
            store your credit card number, CVV, or full card details on our
            servers. We receive from Stripe only a truncated card identifier
            (last 4 digits), card brand, expiration date, and billing address
            for receipt and support purposes.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide and maintain the ViolaWake Console service</li>
            <li>
              Train custom wake word models using your uploaded voice recordings
            </li>
            <li>Process payments and manage your subscription</li>
            <li>
              Send transactional emails (account confirmation, training
              completion notifications, billing receipts)
            </li>
            <li>Improve our training algorithms and service reliability</li>
            <li>Respond to customer support requests</li>
            <li>Detect and prevent fraud or abuse of the service</li>
          </ul>
          <p>
            We do not sell your personal information or voice recordings to third
            parties. We do not use your voice recordings for any purpose other
            than training the specific wake word model you requested.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. The ViolaWake SDK (On-Device)</h2>
          <p>
            The ViolaWake SDK performs all wake word detection entirely on your
            device. No audio data is sent to our servers during inference. The
            SDK does not collect telemetry, analytics, or usage data. It operates
            fully offline once a model file is loaded.
          </p>
        </section>

        <section className="legal-section">
          <h2>5. Data Security</h2>
          <p>
            We implement industry-standard security measures to protect your
            data:
          </p>
          <ul>
            <li>
              All data in transit is encrypted using TLS 1.2 or higher
            </li>
            <li>Voice recordings are stored in encrypted cloud storage (Cloudflare R2)</li>
            <li>Passwords are hashed using bcrypt with per-user salts</li>
            <li>
              API authentication uses JWT tokens with short expiration windows
            </li>
            <li>Access to production infrastructure is restricted to authorized personnel</li>
          </ul>
          <p>
            While we strive to protect your information, no method of electronic
            storage or transmission over the Internet is 100% secure. We cannot
            guarantee absolute security.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. Data Retention</h2>
          <ul>
            <li>
              <strong>Account data:</strong> Retained for the lifetime of your
              account. Deleted within 30 days of account closure.
            </li>
            <li>
              <strong>Voice recordings:</strong> Automatically deleted within
              30 days of successful model training. Immediately deleted upon
              manual deletion request.
            </li>
            <li>
              <strong>Trained models:</strong> Retained until you delete them or
              close your account.
            </li>
            <li>
              <strong>Payment records:</strong> Retained for 7 years as required
              by tax and financial regulations.
            </li>
            <li>
              <strong>Server logs:</strong> Rotated and deleted after 90 days.
            </li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>7. Third-Party Services</h2>
          <p>We use the following third-party services:</p>
          <ul>
            <li>
              <strong>Stripe</strong> for payment processing. Stripe's privacy
              policy is available at{" "}
              <a
                href="https://stripe.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                stripe.com/privacy
              </a>
              .
            </li>
            <li>
              <strong>Cloudflare</strong> for content delivery, DDoS protection,
              and R2 object storage.
            </li>
            <li>
              <strong>Modal.com</strong> for GPU compute during model training.
              Voice recordings are processed transiently on Modal infrastructure
              and are not persisted by Modal.
            </li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>8. Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li>
              <strong>Access</strong> the personal data we hold about you
            </li>
            <li>
              <strong>Correct</strong> inaccurate personal data
            </li>
            <li>
              <strong>Delete</strong> your account and all associated data
            </li>
            <li>
              <strong>Export</strong> your trained models at any time
            </li>
            <li>
              <strong>Withdraw consent</strong> for data processing by closing
              your account
            </li>
            <li>
              <strong>Object</strong> to processing of your data for purposes
              beyond service delivery
            </li>
          </ul>
          <p>
            To exercise any of these rights, contact us at{" "}
            <a href="mailto:privacy@violawake.com">privacy@violawake.com</a>.
            We will respond within 30 days.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. GDPR Compliance (EEA Users)</h2>
          <p>
            If you are located in the European Economic Area (EEA), you have
            additional rights under the General Data Protection Regulation
            (GDPR):
          </p>
          <ul>
            <li>
              <strong>Legal basis for processing:</strong> We process your data
              based on (a) your consent when you create an account, (b)
              contractual necessity to provide the service, and (c) our
              legitimate interest in improving the service.
            </li>
            <li>
              <strong>Data portability:</strong> You may request a copy of your
              data in a machine-readable format.
            </li>
            <li>
              <strong>Right to lodge a complaint:</strong> You may file a
              complaint with your local data protection authority.
            </li>
            <li>
              <strong>Data transfers:</strong> Your data may be processed in the
              United States. We ensure appropriate safeguards are in place for
              international transfers.
            </li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>10. Children's Privacy</h2>
          <p>
            ViolaWake is not directed at children under the age of 16. We do not
            knowingly collect personal information from children. If you believe
            a child has provided us with personal data, please contact us at{" "}
            <a href="mailto:privacy@violawake.com">privacy@violawake.com</a> and
            we will delete it promptly.
          </p>
        </section>

        <section className="legal-section">
          <h2>11. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. When we make
            material changes, we will notify you by email or by posting a notice
            on the Console dashboard. Your continued use of ViolaWake after
            changes take effect constitutes acceptance of the updated policy.
          </p>
        </section>

        <section className="legal-section">
          <h2>12. Contact</h2>
          <p>
            For questions about this Privacy Policy or our data practices,
            contact us at:
          </p>
          <p>
            <strong>Email:</strong>{" "}
            <a href="mailto:privacy@violawake.com">privacy@violawake.com</a>
            <br />
            <strong>General inquiries:</strong>{" "}
            <a href="mailto:hello@violawake.com">hello@violawake.com</a>
          </p>
        </section>

        <div className="legal-footer-nav">
          <Link to="/terms">Terms of Service</Link>
          <Link to="/">Back to Home</Link>
        </div>
      </div>
    </div>
  );
}
